name: visa_mediation_app
description: A Flutter application for visa brokerage system with chat functionality.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  file_picker: ^5.3.3
  url_launcher: ^6.1.12
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/fonts/